### ISSUE TITLE
Sqlite autoincrementing primary keys seem to be broken

### ISSUE THREAD

**Issue by mightybyte** [haskell-beam/beam#493]
Sometime since commit `737b73c6ec1c6aac6386bf9592a02a91f34a9478` it seems that autoincrementing primary keys broke with Sqlite.  Fields that used to be INTEGER are now BIGINT and this seems to have broken sqlite autoincrement.  Running `insert` with `default_` as the primary key expression now fails.

**Comment by mightybyte** [comment]
I was able to fix this by changing `Int` columns to `Int32` (see https://github.com/mightybyte/zeus/pull/36/files).  In case anyone else runs into this, this problem manifested in two different ways.  First with a failure in `autoMigrate` due to a destructive migration even though I hadn't changed the schema.  Second by throwing this error after I manually changed INTEGER fields to BIGINT:

```
SQLite3 returned ErrorConstraint while attempting to perform step: UNIQUE constraint failed:
```

Using BIGINT for primary keys made autoincrement fail for primary keys.

**Comment by kmicklas** [comment]
This was changed in https://github.com/haskell-beam/beam/pull/329 since on a 64 bit system you'd likely assume the SQL translation of `Int` would support 64 bits. Unfortunately I don't think there was any way to fix this (what I would consider to be a) bug without breaking existing users.

Also worth noting that in SQLite these thankfully don't mean anything: https://www.sqlite.org/datatype3.html

**Comment by kmicklas** [comment]
Actually, while `integer` and `bigint` don't mean anything different in a regular column in SQLite, [`integer primary key` is special](https://www.sqlite.org/lang_createtable.html#rowid). Let me see if there's an easy way to fix this.

**Comment by kmicklas** [comment]
@mightybyte Would `SqlSerial Int` work for you? It still maps to `integer primary key` for SQLite.

**Comment by mightybyte** [comment]
Ahh, I was looking for `SqlSerial` but forgot where to find it.  If it maps to `integer` for SQLite, then I assume it will work.  I already changed the above example to use `Int32` though.  I may be doing the migration on another project soon.  I'll give it a try there.

**Comment by kmicklas** [comment]
Closing this in favor of #496.

**Comment by thelissimus** [comment]
@kmicklas

It is broken with `Int64` too because it maps to `BIGINT` by default:

https://github.com/haskell-beam/beam/blob/0c637150f1064fb323d36899e24f2bb2c5debcbd/beam-sqlite/Database/Beam/Sqlite/Syntax.hs#L576-L582

Using `SqlSerial Int64` fixes this, but I don't understand why wouldn't `Int64` map to `INTEGER`. The [SQLite documentation](https://www.sqlite.org/datatype3.html) says:

> - **INTEGER**. The value is a signed integer, stored in 0, 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value.

so... `Int64` should map to `INTEGER`, no? Also, on the section `3.1.1` it states that SQLite ignores much of the types and just represents them as `INTEGER`. I only see disadvantage of broken primary key autoincrement of mapping to `BIGINT`. Is there something I am missing/misunderstood? If the change is plausible then I would gladly contribute and not load the burden to your shoulders if you want.

I have checked out issues/PRs #329 #496 #403 but they seem to be irrelevant; they address `Int` or Postgres related features.
