### ISSUE TITLE
beam-sqlite cannot insert row with only default values

### ISSUE THREAD

**Issue by rycee** [haskell-beam/beam#607]
The below test case fails with

```
    runInsertReturningList with only default values:          FAIL
      test/Database/Beam/Sqlite/Test.hs:9:
      SQLite3 returned ErrorError while attempting to perform prepare "INSERT INTO \"issue607\"() VALUES ()": near ")": syntax error
```

I'm not certain what the best solution is but perhaps the query generator could always output at least one value? If only default values are available then the first default field could be emitted with a `NULL` value.

```patch
diff --git a/beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs b/beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs
index 6b7a180..c71bfb7 100644
--- a/beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs
+++ b/beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs
@@ -22,6 +22,7 @@ tests = testGroup "Selection tests"
   [ expectFail testExceptValues
   , testInRowValues
   , testInsertReturningColumnOrder -- In select tests because the bug was with the selects
+  , testInsertOnlyDefaults
   ]
 
 data Pair f = Pair
@@ -89,3 +90,40 @@ testInsertReturningColumnOrder = testCase "runInsertReturningList with mismatchi
                    , TestTable 4 "blah" "blah" (-1) dateJoined ]
 
     assertEqual "insert values" inserted expected
+
+--
+-- Test insertion into table with all default fields.
+--
+
+data Issue607T f
+  = Issue607
+  { issue607Id :: C f Int32
+  , issue607CreatedAt :: C f LocalTime
+  } deriving (Generic, Beamable)
+
+deriving instance Show (Issue607T Identity)
+deriving instance Eq (Issue607T Identity)
+
+instance Table Issue607T where
+  data PrimaryKey Issue607T f = Issue607Key (C f Int32)
+    deriving (Generic, Beamable)
+  primaryKey = Issue607Key <$> issue607Id
+
+data Issue607Db entity
+  = Issue607Db
+  { tblIssue607 :: entity (TableEntity Issue607T)
+  } deriving (Generic, Database Sqlite)
+
+issue607Db :: DatabaseSettings be Issue607Db
+issue607Db = defaultDbSettings
+
+testInsertOnlyDefaults :: TestTree
+testInsertOnlyDefaults = testCase "runInsertReturningList with only default values" $ do
+  withTestDb $ \conn -> do
+    execute_ conn "CREATE TABLE issue607 ( id INT PRIMARY KEY, created_at TIMESTAMP NOT NULL )"
+    inserted <-
+      runBeamSqlite conn $ runInsertReturningList $
+      insert (tblIssue607 issue607Db) $
+      insertExpressions [ Issue607 default_ default_ ]
+
+    assertEqual "inserted length" (length inserted) 1
```

**Comment by kmicklas** [comment]
I'm trying to figure out if there is even a fully correct and general way to fix this. Unfortunately, SQLite is a big mess. The underlying limitation is the lack of the `DEFAULT` keyword for values. This leaves three workarounds that I can think of:

 * `INSERT INTO table DEFAULT VALUES`: This does the correct thing, but it doesn't support upsert clauses. We'd have to cause a runtime error if all default values are provided for an upsert.
 * `INSERT INTO table (rowid) VALUES (NULL)`: This works with upserts and appears to do the correct thing as long as the table doesn't have a column called `rowid`, and isn't a `WITHOUT ROWID` table.
 * `INSERT INTO table (some_column) VALUES (NULL)`: This isn't actually correct because the default value isn't necessarily null. It's really just a hack that happens to work if the chosen column is an autoincrement primary key.

I'm leaning toward the first option just because it is a strict improvement over the current situation. My last hope is that there will be some way to get a tuple of default values from a carefully crafted `SELECT` expression, so I may investigate that first.

**Comment by rycee** [comment]
Thanks for the help!
