### ISSUE TITLE
Wrong type for `Database.Beam.Postgres.now_` (should be `ZonedTime` instead of `LocalTime`)

### ISSUE THREAD

**Issue by runeksvendsen** [haskell-beam/beam#627]
As far as I can gather from reading the postgres docs, [`Database.Beam.Postgres.now_`](https://hackage.haskell.org/package/beam-postgres-0.5.2.0/docs/Database-Beam-Postgres.html#v:now_) should return a value of type `ZonedTime` and not `LocalTime`.  
These docs https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT say that `now()` is equivalent to `transaction_timestamp()` which is equivalent to `CURRENT_TIMESTAMP` and that "_CURRENT_TIME and CURRENT_TIMESTAMP deliver values with time zone_", whereas the Haskell type `LocalTime` has no time zone component.

**Comment by tathougies** [comment]
I would suggest we think a lot about what these things mean before implementing them. Timestamptz et al do not do what you expect, in that they do not actually store the timezone in the database, but rather cause the time to be reported in postgres's configured timezone. I've always preferred LocalTime for serialization/deserialization because it elides the timezone and lets the user figure it out based on their knowledge of the underlying postgres database.

**Comment by runeksvendsen** [comment]
@tathougies thank you. I had no idea it works this way. Here’s the relevant doc section: https://www.postgresql.org/docs/current/datatype-datetime.html#DATATYPE-TIMEZONES, and quote:

> All timezone-aware dates and times are stored internally in UTC. They are converted to local time in the zone specified by the [TimeZone](https://www.postgresql.org/docs/current/runtime-config-client.html#GUC-TIMEZONE) configuration parameter before being displayed to the client.
