### ISSUE TITLE
`beam` broken in `NixPkgs/haskell-updates` and `NixPkgs` with GHC 9.6

### ISSUE THREAD

**Issue by peterbecich** [haskell-beam/beam#724]
```
NIXPKGS_ALLOW_BROKEN=1 nix build nixpkgs/haskell-updates#haskellPackages.beam --impure
```
produces

```
       > Error: Setup: Encountered missing or private dependencies:
       > base >=4.8 && <4.9
```

I don't know where it is getting this upper bound on `base` `<4.9`.

NixPkgs uses GHC 9.6 / `base 4.18` by default.

If it is solved please remove `beam` here: https://github.com/NixOS/nixpkgs/blob/ec3ec6038a01c6e22637565976ed82e1625fa006/pkgs/development/haskell-modules/configuration-hackage2nix/broken.yaml#L387

**Comment by alexfmpe** [comment]
https://hackage.haskell.org/package/beam says `Deprecated in favor of beam-core` and hasn't had a release in over 5 years.

> If it is solved please remove beam here:

I'll also add that even if `beam-core` itself was marked as broken, maintainers of a lib should not be expected to maintain metadata of their lib on every software distribution's packaging system.

There is overlap but those are very different roles. 

I know because I perform both for a number of libs (not beam ones)
